
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react-swc";
import path from "path";
import { componentTagger } from "lovable-tagger";

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => ({
  server: {
    host: "::",
    port: 8080,
    headers: {
      // Content Security Policy with CSP reporting and nonce support
      'Content-Security-Policy': `
        default-src 'self';
        script-src 'self' 'nonce-{NONCE}' https://cdn.gpteng.co;
        style-src 'self' 'unsafe-inline';
        img-src 'self' data: blob: https:;
        connect-src 'self' ws://localhost:* wss://localhost:*;
        frame-ancestors 'self';
        form-action 'self';
        base-uri 'self';
        object-src 'none';
        report-uri /api/csp-report;
        report-to endpoint-1;
      `.replace(/\s+/g, ' ').trim(),
      
      // Report-To header for CSP reporting
      'Report-To': '{"group":"endpoint-1","max_age":10886400,"endpoints":[{"url":"/api/csp-report"}]}',
      
      // HSTS with 2 year duration (63072000 seconds)
      'Strict-Transport-Security': 'max-age=63072000; includeSubDomains',
      
      // Referrer Policy
      'Referrer-Policy': 'strict-origin-when-cross-origin',
      
      // Prevent MIME type sniffing
      'X-Content-Type-Options': 'nosniff',
      
      // CORP
      'Cross-Origin-Resource-Policy': 'same-origin',
      
      // More restrictive CORS
      'Access-Control-Allow-Origin': 'https://cdn.gpteng.co',
      'Access-Control-Allow-Methods': 'GET',
      
      // Additional security headers
      'X-Frame-Options': 'SAMEORIGIN',
      'X-XSS-Protection': '1; mode=block',
      'Permissions-Policy': 'camera=(), microphone=(), geolocation=()',
    }
  },
  plugins: [
    react({
      // Pass the nonce to the script tags generated by React
      jsxImportSource: '@emotion/react',
      babel: {
        plugins: [
          ['@emotion/babel-plugin', {
            cssPropOptimization: true,
          }],
        ],
      },
    }),
    mode === 'development' &&
    componentTagger(),
  ].filter(Boolean),
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
}));
